[package]
name = "monitord"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.217"
sysinfo = "0.33.1"
tokio = { version = "1.43.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
zbus = "5.3.0"
