[package]
name = "cosmic-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
freedesktop_entry_parser = "1.3.0"
raw-cpuid = "11.2.0"
cpu-freq = "0.0.2"
sysinfo = "0.32.0"

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
default-features = false
features = ["a11y", "tokio", "winit", "wgpu", "xdg-portal", "multi-window"]
